Updated the GitHub workflows and/or the README file to the latest versions.

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -89,9 +89,9 @@ jobs:
           then
             config='{"config":[
             {"os":"windows-latest", "r":"release", "timeout":360, "flags":"binaries"},
-            {"os":"macOS-latest", "r":"release", "timeout":360, "flags":"binaries"},
+            {"os":"macOS-latest", "r":"release", "timeout":360, "flags":"binaries, ubsan"},
             {"os":"ubuntu-20.04", "r":"release", "rspm":"https://packagemanager.rstudio.com/cran/__linux__/focal/latest", "timeout":360, "flags":"full, ubsan, debug"},
-            {"os":"ubuntu-20.04", "r":"devel", "rspm":"https://packagemanager.rstudio.com/cran/__linux__/focal/latest", "timeout":360, "flags":"vignettes"},
+            {"os":"ubuntu-20.04", "r":"devel", "rspm":"https://packagemanager.rstudio.com/cran/__linux__/focal/latest", "timeout":360, "flags":"vignettes, remote"},
             {"os":"ubuntu-20.04", "r":"release", "rspm":"https://packagemanager.rstudio.com/cran/__linux__/focal/latest", "timeout":360, "flags":"full, covr"}]}'
           elif [[ "${{ env.FOUND_PUBLIC }}" != '0' ]] # Private with no public analogue: reduced set.
           then
@@ -189,6 +189,7 @@ jobs:
         run: |
           remotes::install_cran("tinytex")
           tinytex:::install_yihui_pkgs()
+          tinytex::tlmgr_install("makeindex")
         shell: Rscript {0}
 
       - name: Build
@@ -214,7 +215,7 @@ jobs:
         if: contains(matrix.config.flags, 'covr') == false
         timeout-minutes: ${{ matrix.config.timeout }}
         env:
-          _R_CHECK_CRAN_INCOMING_REMOTE_: false
+          _R_CHECK_CRAN_INCOMING_REMOTE_: ${{ contains(matrix.config.flags, 'remote') }}
           _R_CHECK_FORCE_SUGGESTS_: false
           ENABLE_statnet_TESTS: ${{ contains(matrix.config.flags, 'full') }}
           R_VIGNETTES: ${{ contains(matrix.config.flags, 'vignettes') }}
@@ -228,6 +229,10 @@ jobs:
           }else{
             check_args <- c("--no-manual", "--as-cran", "--ignore-vignettes")
             build_args <- c("--no-manual", "--no-build-vignettes")
+          }
+
+          if(Sys.getenv("ENABLE_statnet_TESTS") == "true"){
+            check_args <- c(check_args, "--run-donttest")
           }
 
           error_on <- if(Sys.getenv("FAIL_ON_WARN") == "true") "warning" else "error"
@@ -250,13 +255,18 @@ jobs:
 
       - name: Check UBSAN output
         if: contains(matrix.config.flags, 'ubsan')
+        # NB: xargs -r only works in GNU, so not on MacOS.
         run: |
-          find check/ -name '*.Rout' -print0 | xargs -r -0 grep -E '\.[hc]:[0-9]+:[0-9]+: +runtime error:' > check/ubsan.err || true
-          if [ -s check/ubsan.err ]
+          find check/ -name '*.Rout' -print0 > check/Rout.list
+          if [ -s check/Rout.list ]
           then
-            echo "UBSAN errors:" >&2
-            cat check/ubsan.err >&2
-            exit 1
+            cat check/Rout.list | xargs -0 grep -E '\.[hc]:[0-9]+:[0-9]+: +runtime error:' > check/ubsan.err || true
+            if [ -s check/ubsan.err ]
+            then
+              echo "UBSAN errors:" >&2
+              cat check/ubsan.err >&2
+              exit 1
+            fi
           fi
         shell: bash
         
@@ -268,6 +278,11 @@ jobs:
           path: |
             check
             !check/*/00_pkg_src
+
+      - name: Preinstall package to work around an issue in covr # can be removed after covr update
+        if: contains(matrix.config.flags, 'covr')
+        run: R CMD INSTALL .
+        shell: bash
 
       - name: Test coverage
         if: contains(matrix.config.flags, 'covr')
